

# Build settings
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 theme: jekyll-theme-architect
 gfm_quirks: paragraph_end

#Site Setting
title: [陈旭恒 博客]
description: [Not LOve Me]
