#设置jekll配置
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache

# Build settings
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 theme: jekyll-theme-architect
 gfm_quirks: paragraph_end

#Site Setting
title: [陈旭恒 博客]
description: [Not LOve Me]
